services:
  db:
    image: mysql:latest
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"

  webserver:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    container_name: Practice_1

volumes:
  db_data: